export default function RandomEducation() {
  return (
    <div className="space-y-8">
      {/* What is a Random Number? */}
      <div className="bg-white rounded-lg shadow-md p-6">
        <h3 className="text-2xl font-bold text-gray-800 mb-4">
          What is a Random Number?
        </h3>
        <div className="prose max-w-none">
          <p className="text-gray-700 mb-4">
            A random number is a number chosen from a pool of limited or
            unlimited numbers that has no discernible pattern for prediction.
            The pool of numbers is almost always independent from each other.
            However, the pool of numbers may follow a specific distribution.
          </p>

          <p className="text-gray-700 mb-4">
            For example, the height of the students in a school tends to follow
            a normal distribution around the median height. If the height of a
            student is picked at random, the picked number has a higher chance
            to be closer to the median height than being classified as very tall
            or very short.
          </p>

          <p className="text-gray-700">
            The random number generators above assume that the numbers generated
            are independent of each other, and will be evenly spread across the
            whole range of possible values.
          </p>
        </div>
      </div>

      {/* Random Number Generators */}
      <div className="bg-white rounded-lg shadow-md p-6">
        <h3 className="text-2xl font-bold text-gray-800 mb-4">
          Random Number Generators
        </h3>
        <div className="prose max-w-none">
          <p className="text-gray-700 mb-4">
            A random number generator, like the ones above, is a device that can
            generate one or many random numbers within a defined scope. Random
            number generators can be hardware based or pseudo-random number
            generators.
          </p>

          <p className="text-gray-700 mb-4">
            Hardware based random-number generators can involve the use of a
            dice, a coin for flipping, or many other devices.
          </p>

          <div className="bg-blue-50 border border-blue-200 rounded p-4 mb-4">
            <h4 className="font-semibold mb-2">
              Types of Random Number Generators:
            </h4>
            <ul className="list-disc list-inside space-y-1">
              <li>
                <strong>Hardware-based:</strong> Use physical phenomena like
                dice, coins, or electronic noise
              </li>
              <li>
                <strong>Pseudo-random:</strong> Use mathematical algorithms to
                generate sequences
              </li>
              <li>
                <strong>True random:</strong> Based on quantum phenomena and
                atmospheric noise
              </li>
            </ul>
          </div>
        </div>
      </div>

      {/* Pseudo-Random Number Generators */}
      <div className="bg-white rounded-lg shadow-md p-6">
        <h3 className="text-2xl font-bold text-gray-800 mb-4">
          Pseudo-Random Number Generators
        </h3>
        <div className="prose max-w-none">
          <p className="text-gray-700 mb-4">
            A pseudo-random number generator is an algorithm for generating a
            sequence of numbers whose properties approximate the properties of
            sequences of random numbers. Computer based random number generators
            are almost always pseudo-random number generators.
          </p>

          <p className="text-gray-700 mb-4">
            Yet, the numbers generated by pseudo-random number generators are
            not truly random. Likewise, our generators above are also
            pseudo-random number generators. The random numbers generated are
            sufficient for most applications yet they should not be used for
            cryptographic purposes.
          </p>

          <div className="bg-yellow-50 border border-yellow-200 rounded p-4 mb-4">
            <h4 className="font-semibold mb-2">Important Note:</h4>
            <p className="text-sm">
              The random numbers generated by this tool are suitable for general
              purposes, simulations, games, and educational use, but should not
              be used for cryptographic applications, security purposes, or any
              application where true randomness is critical.
            </p>
          </div>
        </div>
      </div>

      {/* True Random Numbers */}
      <div className="bg-white rounded-lg shadow-md p-6">
        <h3 className="text-2xl font-bold text-gray-800 mb-4">
          True Random Numbers
        </h3>
        <div className="prose max-w-none">
          <p className="text-gray-700 mb-4">
            True random numbers are based on physical phenomena such as
            atmospheric noise, thermal noise, and other quantum phenomena.
            Methods that generate true random numbers also involve compensating
            for potential biases caused by the measurement process.
          </p>

          <div className="bg-green-50 border border-green-200 rounded p-4">
            <h4 className="font-semibold mb-2">Sources of True Randomness:</h4>
            <ul className="list-disc list-inside space-y-1 text-sm">
              <li>Atmospheric noise from radio signals</li>
              <li>Thermal noise in electronic circuits</li>
              <li>Quantum mechanical phenomena</li>
              <li>Radioactive decay</li>
              <li>Photon emission timing</li>
            </ul>
          </div>
        </div>
      </div>

      {/* Applications and Use Cases */}
      <div className="bg-white rounded-lg shadow-md p-6">
        <h3 className="text-2xl font-bold text-gray-800 mb-4">
          Applications and Use Cases
        </h3>
        <div className="prose max-w-none">
          <div className="grid md:grid-cols-2 gap-6">
            <div>
              <h4 className="font-semibold mb-2 text-green-600">
                Suitable for Pseudo-Random:
              </h4>
              <ul className="list-disc list-inside space-y-1 text-sm">
                <li>Games and simulations</li>
                <li>Statistical sampling</li>
                <li>Monte Carlo methods</li>
                <li>Educational purposes</li>
                <li>General programming</li>
                <li>A/B testing</li>
                <li>Random selection</li>
              </ul>
            </div>

            <div>
              <h4 className="font-semibold mb-2 text-red-600">
                Requires True Random:
              </h4>
              <ul className="list-disc list-inside space-y-1 text-sm">
                <li>Cryptographic keys</li>
                <li>Security tokens</li>
                <li>Password generation</li>
                <li>Lottery systems</li>
                <li>Scientific research</li>
                <li>Financial modeling</li>
                <li>Gambling applications</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
